### ISSUE TITLE
Swift PM Support

### ISSUE THREAD

**Issue by filip-sakel** [compnerd/uswift#83]
Is it possible to support uswift as a package that could be used by embedded apps? These apps would use `-parse-stdlib` and then manually import uswift as their standard library.

**Comment by compnerd** [comment]
No, that is not something that I intend to support.  I am interested in adding support for building with bazel, but this will not support SPM as this sits far too low in the stack.  In theory, it should be possible to have SPM depend on this.  The circularity would make this far more complicated.
